/** Markdown intro rendered at the top of Scalar / OpenAPI info.description */

export function buildShipflowApiDescription(clientUrl: string, baseUrl: string): string {
  return [
    "# ShipFlow API Reference",
    "",
    "> **AI-assisted product delivery platform** — move features from **request → PRD → tasks → code → AI review → human approval → ship**.",
    "",
    "---",
    "",
    "## Judge quick-start",
    "",
    "| # | Action | URL |",
    "|---|--------|-----|",
    "| 1 | Open web app | " + clientUrl + " |",
    "| 2 | **One-click demo login** | " + clientUrl + "/api-auth/demo?next=/brief |",
    "| 3 | **This Scalar UI** | " + baseUrl + "/docs |",
    "| 4 | Pipeline overview | " + clientUrl + "/brief |",
    "| 5 | External intake hub | " + clientUrl + "/inbox |",
    "| 6 | Feature requests hub | " + clientUrl + "/requests |",
    "| 7 | Engineering Kanban | " + clientUrl + "/tasks |",
    "| 8 | ShipFlow Agent (33 tools, SSE) | " + clientUrl + "/agent |",
    "| 9 | Billing | " + clientUrl + "/billing |",
    "| 10 | Connect GitHub App | " + clientUrl + "/settings |",
    "| 11 | MCP `tools/list` (33 tools) | `POST " + baseUrl + "/mcp` |",
    "",
    "Walkthrough: **`JUDGE_WALKTHROUGH.md`** · Demo script: **`DEMO.md`** · Full guide: **`DOCS.md`**",
    "",
    "---",
    "",
    "## Core delivery loop",
    "",
    "```",
    "Feature Request → PRD → Tasks → Code → AI Review → Fixes → Re-Review → Human Approval → Ship",
    "```",
    "",
    "| Phase | Statuses |",
    "|-------|----------|",
    "| Discovery | submitted, clarifying, prd_generating, prd_ready |",
    "| Planning | planning, plan_approved |",
    "| Development | in_development, pr_open |",
    "| AI Review | ai_review, fix_needed |",
    "| Release | human_review, approved, shipped |",
    "",
    "---",
    "",
    "## Architecture",
    "",
    "```",
    "┌─────────────┐     tRPC/REST      ┌──────────────┐     GitHub App      ┌─────────────┐",
    "│  Next.js    │ ─────────────────► │  ShipFlow    │ ──────────────────► │ Repos + PRs │",
    "│  /requests  │   /api/* + cookies │  Express API │   webhooks (HMAC)   │             │",
    "│  /agent     │ ◄── SSE stream ─── │  + MCP (19)  │                     └─────────────┘",
    "│  /brief     │                    │  + Agent     │",
    "└─────────────┘                    └──────────────┘",
    "                                           │",
    "                                           ▼",
    "                                    Postgres (features, PRDs,",
    "                                    tasks, agent sessions, GitHub)",
    "```",
    "",
    "| Layer | Technology |",
    "|-------|------------|",
    "| Frontend | Next.js 16, tRPC client, custom Qship design system |",
    "| API | Express, tRPC v11, trpc-to-openapi → **this Scalar doc** |",
    "| Auth | BetterAuth — email/password + Google OAuth |",
    "| AI | OpenAI gpt-4o-mini — triage, PRD, tasks, pre-ship review |",
    "| MCP | MCP 2024-11-05 — **33 ShipFlow tools** (agent parity verified in CI) |",
    "",
    "---",
    "",
    "## Authentication",
    "",
    "### Browser session (web app)",
    "",
    "1. Sign in at " + clientUrl + "/sign-in (Google OAuth or email/password)",
    "2. BetterAuth sets httpOnly session cookies",
    "3. Protected tRPC/OpenAPI routes require a valid session cookie",
    "",
    "### Demo login (judges)",
    "",
    "1. Run `pnpm db:seed` once after migrations",
    "2. Set `DEMO_LOGIN_ENABLED=true` in `.env`",
    "3. Open " + clientUrl + "/api-auth/demo?next=/brief",
    "",
    "| Field | Default |",
    "|-------|---------|",
    "| Email | `demo@qship.dev` |",
    "| Password | `DemoPass123!` |",
    "",
    "Demo AI limits: 3 agent runs per session (configurable via `NEXT_PUBLIC_DEMO_AGENT_LIMIT`).",
    "",
    "### Headless / MCP",
    "",
    "```",
    "Authorization: Bearer <SHIPFLOW_MCP_API_KEY>",
    "```",
    "",
    "Must match env `SHIPFLOW_MCP_USER_ID` — scoped to one user, no arbitrary impersonation.",
    "",
    "---",
    "",
    "## MCP server (33 tools)",
    "",
    "**Endpoint:** `POST " + baseUrl + "/mcp` (JSON-RPC 2.0 / MCP 2024-11) — **33 tools**",
    "",
    "| Category | Tools |",
    "|----------|-------|",
    "| Workspace | `get_workspace`, `get_pipeline_summary` |",
    "| Features | `list_feature_requests`, `get_feature_request`, `create_feature_request`, `triage_feature_request`, `generate_feature_prd`, `generate_feature_tasks`, `add_clarification`, `update_feature_status`, `get_feature_delivery` |",
    "| Review | `run_ai_review`, `list_ai_reviews`, `get_review_delta`, `get_review_stats`, `get_review_loop_health`, `resolve_review_issue` |",
    "| Approval | `request_human_review`, `approve_feature`, `reject_feature`, `request_changes`, `get_approval_history`, `get_approval_briefing`, `analyze_change_request` |",
    "| Analytics | `predict_delivery_timeline`, `check_pipeline_duplicates`, `get_pipeline_health`, `get_developer_onboarding_guide` |",
    "| Kanban | `update_engineering_task_status` |",
    "| Intake | `intake_from_channel`, `check_existing_capability` |",
    "| GitHub | `github_connection_status`, `list_github_repositories` |",
    "",
    "**Total: 33 tools** · Manifest: **`mcp-server.json`** · CI parity: `packages/services/ai/tool-parity.test.ts`",
    "",
    "---",
    "",
    "## Agent (SSE streaming)",
    "",
    "| Endpoint | Method | Purpose |",
    "|----------|--------|---------|",
    "| `/agent/stream` | POST | SSE streaming agent with 33 ShipFlow tools |",
    "",
    "Rate limit: 20 requests/min/user. Guardrails: prompt injection detection, token budget, human-in-the-loop prompts for sensitive actions.",
    "",
    "---",
    "",
    "## GitHub integration",
    "",
    "| Component | Details |",
    "|-----------|---------|",
    "| GitHub App | Install from Settings → lists repos via Octokit |",
    "| Webhook | `POST /webhooks/github` — HMAC-SHA256 verified (`x-hub-signature-256`) |",
    "| tRPC | `github.connectionStatus`, `github.getInstallUrl`, `github.listRepositories`, `github.syncInstallation` |",
    "",
    "---",
    "",
    "## Related docs",
    "",
    "| Doc | Purpose |",
    "|-----|---------|",
    "| `README.md` | Setup, stack, deployment |",
    "| `DEMO.md` | 3-minute judge walkthrough + curl examples |",
    "| `DOCS.md` | Full technical reference |",
    "| `JUDGE_WALKTHROUGH.md` | Timed scoring checklist |",
    "| `HACKATHON_SUBMISSION.md` | One-pager + rubric map |",
    "",
  ].join("\n");
}
